### ISSUE TITLE
Move STORAGE_MOUNT_POINT from DataStorage to config file

### ISSUE THREAD

**Issue by kevinyamauchi** [czbiohub/imagingDB#79]
I think users may have different mount points for the image data store on their system. Therefore, I think we should move the data store path from a [constant in `DataStorage`](https://github.com/czbiohub/imagingDB/blob/80d2e81f591ad9d43c0929a93570638be3da5544/imaging_db/filestorage/data_storage.py#L5) to a field in the config file.

**Comment by jennyfolkesson** [comment]
Good point. There is an option to input your own mount point as a command line argument, and I was debating with myself what should go as an argument and what goes in the config (https://github.com/czbiohub/imagingDB/issues/72).
I agree with you, storage_access is probably a good one for the config. I'd still like to have a default value though since most of us are mac users so data_lg would end up in Volumes/.
Should I also move nbr_workers and storage to config do you think?

**Comment by jennyfolkesson** [comment]
There's still a default mount point, but you can specify your own mount point in the config file with https://github.com/czbiohub/imagingDB/pull/78.

**Comment by kevinyamauchi** [comment]
Thanks! That works for me!
